# Generated by Django 5.2.1 on 2025-05-23 21:03

from django.db import migrations


def add_record_purposes(apps, _):
    Purpose = apps.get_model('records', 'Purpose')
    for name in ['Бизнес', 'Личное', 'Налог']:
        Purpose.objects.create(name=name)

    Type = apps.get_model('records', 'Type')
    for name in ['Пополнение', 'Списание']:
        Type.objects.create(name=name)
    
    categories = { 'Инфраструктура': ['VPS', 'Proxy'], 'Маркетинг': ['Farpost', 'Avito']}
    Category = apps.get_model('records', 'Category')
    SubCategory = apps.get_model('records', 'SubCategory')
    for category, subcategories in categories.items():
        category_obj = Category.objects.create(name=category)

        for subcategory in subcategories:
            SubCategory.objects.create(category=category_obj, name=subcategory)


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_record_purposes),
    ]
